# Generated by Django 4.1.7 on 2023-02-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='center_image',
            field=models.CharField(default='center_image', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='left_image',
            field=models.CharField(default='left_image', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='right_image',
            field=models.CharField(default='right_image', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
